/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as IasRouteImport } from './routes/ias'
import { Route as FuncoesRouteImport } from './routes/funcoes'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSidekiqRouteImport } from './routes/super-admin.sidekiq'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminPlatformAppsRouteImport } from './routes/super-admin.platform-apps'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as SuperAdminInstanceHealthRouteImport } from './routes/super-admin.instance-health'
import { Route as SuperAdminAgentBotsRouteImport } from './routes/super-admin.agent-bots'
import { Route as SuperAdminAccountsRouteImport } from './routes/super-admin.accounts'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IasRoute = IasRouteImport.update({
  id: '/ias',
  path: '/ias',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncoesRoute = FuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSidekiqRoute = SuperAdminSidekiqRouteImport.update({
  id: '/sidekiq',
  path: '/sidekiq',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlatformAppsRoute = SuperAdminPlatformAppsRouteImport.update({
  id: '/platform-apps',
  path: '/platform-apps',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminInstanceHealthRoute =
  SuperAdminInstanceHealthRouteImport.update({
    id: '/instance-health',
    path: '/instance-health',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminAgentBotsRoute = SuperAdminAgentBotsRouteImport.update({
  id: '/agent-bots',
  path: '/agent-bots',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAccountsRoute = SuperAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/funcoes': typeof FuncoesRoute
  '/ias': typeof IasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sla': typeof SlaRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/agent-bots': typeof SuperAdminAgentBotsRoute
  '/super-admin/instance-health': typeof SuperAdminInstanceHealthRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/platform-apps': typeof SuperAdminPlatformAppsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/sidekiq': typeof SuperAdminSidekiqRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/funcoes': typeof FuncoesRoute
  '/ias': typeof IasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sla': typeof SlaRoute
  '/whatsapp': typeof WhatsappRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/agent-bots': typeof SuperAdminAgentBotsRoute
  '/super-admin/instance-health': typeof SuperAdminInstanceHealthRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/platform-apps': typeof SuperAdminPlatformAppsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/sidekiq': typeof SuperAdminSidekiqRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/funcoes': typeof FuncoesRoute
  '/ias': typeof IasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sla': typeof SlaRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/agent-bots': typeof SuperAdminAgentBotsRoute
  '/super-admin/instance-health': typeof SuperAdminInstanceHealthRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/platform-apps': typeof SuperAdminPlatformAppsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/sidekiq': typeof SuperAdminSidekiqRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/automacoes'
    | '/configuracoes'
    | '/contatos'
    | '/conversas'
    | '/funcoes'
    | '/ias'
    | '/relatorios'
    | '/sla'
    | '/super-admin'
    | '/whatsapp'
    | '/super-admin/accounts'
    | '/super-admin/agent-bots'
    | '/super-admin/instance-health'
    | '/super-admin/login'
    | '/super-admin/platform-apps'
    | '/super-admin/settings'
    | '/super-admin/sidekiq'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/automacoes'
    | '/configuracoes'
    | '/contatos'
    | '/conversas'
    | '/funcoes'
    | '/ias'
    | '/relatorios'
    | '/sla'
    | '/whatsapp'
    | '/super-admin/accounts'
    | '/super-admin/agent-bots'
    | '/super-admin/instance-health'
    | '/super-admin/login'
    | '/super-admin/platform-apps'
    | '/super-admin/settings'
    | '/super-admin/sidekiq'
    | '/super-admin/users'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/automacoes'
    | '/configuracoes'
    | '/contatos'
    | '/conversas'
    | '/funcoes'
    | '/ias'
    | '/relatorios'
    | '/sla'
    | '/super-admin'
    | '/whatsapp'
    | '/super-admin/accounts'
    | '/super-admin/agent-bots'
    | '/super-admin/instance-health'
    | '/super-admin/login'
    | '/super-admin/platform-apps'
    | '/super-admin/settings'
    | '/super-admin/sidekiq'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AutomacoesRoute: typeof AutomacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  ConversasRoute: typeof ConversasRoute
  FuncoesRoute: typeof FuncoesRoute
  IasRoute: typeof IasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SlaRoute: typeof SlaRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ias': {
      id: '/ias'
      path: '/ias'
      fullPath: '/ias'
      preLoaderRoute: typeof IasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcoes': {
      id: '/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof FuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/sidekiq': {
      id: '/super-admin/sidekiq'
      path: '/sidekiq'
      fullPath: '/super-admin/sidekiq'
      preLoaderRoute: typeof SuperAdminSidekiqRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/platform-apps': {
      id: '/super-admin/platform-apps'
      path: '/platform-apps'
      fullPath: '/super-admin/platform-apps'
      preLoaderRoute: typeof SuperAdminPlatformAppsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/instance-health': {
      id: '/super-admin/instance-health'
      path: '/instance-health'
      fullPath: '/super-admin/instance-health'
      preLoaderRoute: typeof SuperAdminInstanceHealthRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/agent-bots': {
      id: '/super-admin/agent-bots'
      path: '/agent-bots'
      fullPath: '/super-admin/agent-bots'
      preLoaderRoute: typeof SuperAdminAgentBotsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/accounts': {
      id: '/super-admin/accounts'
      path: '/accounts'
      fullPath: '/super-admin/accounts'
      preLoaderRoute: typeof SuperAdminAccountsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminAccountsRoute: typeof SuperAdminAccountsRoute
  SuperAdminAgentBotsRoute: typeof SuperAdminAgentBotsRoute
  SuperAdminInstanceHealthRoute: typeof SuperAdminInstanceHealthRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  SuperAdminPlatformAppsRoute: typeof SuperAdminPlatformAppsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSidekiqRoute: typeof SuperAdminSidekiqRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAccountsRoute: SuperAdminAccountsRoute,
  SuperAdminAgentBotsRoute: SuperAdminAgentBotsRoute,
  SuperAdminInstanceHealthRoute: SuperAdminInstanceHealthRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  SuperAdminPlatformAppsRoute: SuperAdminPlatformAppsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSidekiqRoute: SuperAdminSidekiqRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  AutomacoesRoute: AutomacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  ConversasRoute: ConversasRoute,
  FuncoesRoute: FuncoesRoute,
  IasRoute: IasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SlaRoute: SlaRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
