// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbryznmmalyknxzpevql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impicnl6bm1tYWx5a254enBldnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDkzMjYsImV4cCI6MjA4OTUyNTMyNn0.97byah1x2cKHBtlRqBtlzDL0vqYcLKm1P6RyfKV4tLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});